#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf "$DIR/gitconfig" ~/.gitconfig
ln -sf "$DIR/zshrc" ~/.zshrc

mkdir -p ~/.ssh && ln -sf "$DIR/sshconfig" ~/.ssh/config && chmod 700 ~/.ssh
